### ISSUE TITLE
Изучить работу похожего дискорд-бота

### ISSUE THREAD

**Issue by DantesFonCake** [TreploOrg/Treplo_Main#3]
Изучить работу похожего по ожидаемому функционалу дискорд-бота [Ear Tensifier](https://github.com/Tetracyl/EarTensifier)  

Результаты представить в любом удобном виде (желательно кроме устного)

**Comment by kekis01** [comment]
Очень много кода, я поверхностно только пробежался...

[eartensifier.docx](https://github.com/TreploOrg/Treplo_Main/files/11523165/eartensifier.docx)
