### ISSUE TITLE
Проектирование фронта/панели управления

### ISSUE THREAD

**Issue by DantesFonCake** [TreploOrg/Treplo_Main#8]
Начать проектирование фронта с которого можно будет управлять ботом
Проектирование включает - макеты дизайна, псевдо макеты апи

**Comment by kekis01** [comment]
https://www.figma.com/file/uHk7r0mQrcioIRM072Be3G/Treplo?type=design&node-id=0%3A1&t=pk60Uksk3gpT1Mpz-1

**Comment by Fobur** [comment]
Пойдет
